version: "3.9"

services:
  database:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: SQL_work!ng_Ott3rs
      MYSQL_DATABASE: slam
    ports:
      - "3307:3306"
    networks:
      - backend
  
  slam:
    image: slam:latest
    networks:
      - backend

  api:
    image: slam-api:latest
    ports:
      - "8081:8080"
    networks:
      - frontend
      - backend